### ISSUE TITLE
negative latitude / longitude values are not processed correctly

### ISSUE THREAD

**Issue by arneschween** [DeepAQ/SmartIntel#3]
Canidate pictures with negative longitude or latitude values are processed as if having postive ones. So OSM links are misleading and the distance from candidate to photo is displayed with far to high values.

**Comment by DeepAQ** [comment]
Script is updated, thanks for reporting. Please reopen this issue if problem still exists.

**Comment by arneschween** [comment]
fixed, perfect, thx!
